print("Welcome to the Band Name Generator")
print("What's the name of the city you grew up in?")
name_1 = input(" ")
print("What's your pet's name")
name_2 = input(" ")
print("Your name could be " + name_1 +" " + name_2)